name: chrome
on:
  schedule:
    - cron: '0 14 * * 1-5'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install
        env:
          email: ${{ secrets.email }}
          password: ${{ secrets.password }}
          employeeId: ${{ secrets.employeeId }}
        run: |
          npm install
          npm run cy:ci
        working-directory: ./
